export const bibleBooks = {
  oldTestament: [
    { name: "Genesis", slug: "genesis" },
    { name: "Exodus", slug: "exodus" },
    { name: "Leviticus", slug: "leviticus" },
    { name: "Numbers", slug: "numbers" },
    { name: "Deuteronomy", slug: "deuteronomy" },
    { name: "Joshua", slug: "joshua" },
    { name: "Judges", slug: "judges" },
    { name: "Ruth", slug: "ruth" },
    { name: "1 Samuel", slug: "1-samuel" },
    { name: "2 Samuel", slug: "2-samuel" },
    { name: "1 Kings", slug: "1-kings" },
    { name: "2 Kings", slug: "2-kings" },
    { name: "1 Chronicles", slug: "1-chronicles" },
    { name: "2 Chronicles", slug: "2-chronicles" },
    { name: "Ezra", slug: "ezra" },
    { name: "Nehemiah", slug: "nehemiah" },
    { name: "Esther", slug: "esther" },
    { name: "Job", slug: "job" },
    { name: "Psalms", slug: "psalms" },
    { name: "Proverbs", slug: "proverbs" },
    { name: "Ecclesiastes", slug: "ecclesiastes" },
    { name: "Song of Solomon", slug: "song-of-solomon" },
    { name: "Isaiah", slug: "isaiah" },
    { name: "Jeremiah", slug: "jeremiah" },
    { name: "Lamentations", slug: "lamentations" },
    { name: "Ezekiel", slug: "ezekiel" },
    { name: "Daniel", slug: "daniel" },
    { name: "Hosea", slug: "hosea" },
    { name: "Joel", slug: "joel" },
    { name: "Amos", slug: "amos" },
    { name: "Obadiah", slug: "obadiah" },
    { name: "Jonah", slug: "jonah" },
    { name: "Micah", slug: "micah" },
    { name: "Nahum", slug: "nahum" },
    { name: "Habakkuk", slug: "habakkuk" },
    { name: "Zephaniah", slug: "zephaniah" },
    { name: "Haggai", slug: "haggai" },
    { name: "Zechariah", slug: "zechariah" },
    { name: "Malachi", slug: "malachi" },
  ],
  newTestament: [
    { name: "Matthew", slug: "matthew" },
    { name: "Mark", slug: "mark" },
    { name: "Luke", slug: "luke" },
    { name: "John", slug: "john" },
    { name: "Acts", slug: "acts" },
    { name: "Romans", slug: "romans" },
    { name: "1 Corinthians", slug: "1-corinthians" },
    { name: "2 Corinthians", slug: "2-corinthians" },
    { name: "Galatians", slug: "galatians" },
    { name: "Ephesians", slug: "ephesians" },
    { name: "Philippians", slug: "philippians" },
    { name: "Colossians", slug: "colossians" },
    { name: "1 Thessalonians", slug: "1-thessalonians" },
    { name: "2 Thessalonians", slug: "2-thessalonians" },
    { name: "1 Timothy", slug: "1-timothy" },
    { name: "2 Timothy", slug: "2-timothy" },
    { name: "Titus", slug: "titus" },
    { name: "Philemon", slug: "philemon" },
    { name: "Hebrews", slug: "hebrews" },
    { name: "James", slug: "james" },
    { name: "1 Peter", slug: "1-peter" },
    { name: "2 Peter", slug: "2-peter" },
    { name: "1 John", slug: "1-john" },
    { name: "2 John", slug: "2-john" },
    { name: "3 John", slug: "3-john" },
    { name: "Jude", slug: "jude" },
    { name: "Revelation", slug: "revelation" },
  ],
}
