export const bibleBooks = {
  oldTestament: [
    { name: "Genesis", slug: "genesis" },
    { name: "Exodus", slug: "exodus" },
    { name: "Leviticus", slug: "leviticus" },
    { name: "Numbers", slug: "numbers" },
    { name: "Deuteronomy", slug: "deuteronomy" },
    { name: "Joshua", slug: "joshua" },
    { name: "Judges", slug: "judges" },
    { name: "Ruth", slug: "ruth" },
    { name: "1 Samuel", slug: "1-samuel" },
    { name: "2 Samuel", slug: "2-samuel" },
    { name: "1 Kings", slug: "1-kings" },
    { name: "2 Kings", slug: "2-kings" },
    { name: "1 Chronicles", slug: "1-chronicles" },
    { name: "2 Chronicles", slug: "2-chronicles" },
    { name: "Ezra", slug: "ezra" },
    { name: "Nehemiah", slug: "nehemiah" },
    { name: "Esther", slug: "esther" },
    { name: "Job", slug: "job" },
    { name: "Psalms", slug: "psalms" },
    { name: "Proverbs", slug: "proverbs" },
    { name: "Ecclesiastes", slug: "ecclesiastes" },
    { name: "Song of Solomon", slug: "song-of-solomon" },
    { name: "Isaiah", slug: "isaiah" },
    { name: "Jeremiah", slug: "jeremiah" },
    { name: "Lamentations", slug: "lamentations" },
    { name: "Ezekiel", slug: "ezekiel" },
    { name: "Daniel", slug: "daniel" },
    { name: "Hosea", slug: "hosea" },
    { name: "Joel", slug: "joel" },
    { name: "Amos", slug: "amos" },
    { name: "Obadiah", slug: "obadiah" },
    { name: "Jonah", slug: "jonah" },
    { name: "Micah", slug: "micah" },
    { name: "Nahum", slug: "nahum" },
    { name: "Habakkuk", slug: "habakkuk" },
    { name: "Zephaniah", slug: "zephaniah" },
    { name: "Haggai", slug: "haggai" },
    { name: "Zechariah", slug: "zechariah" },
    { name: "Malachi", slug: "malachi" },
  ],
  newTestament: [
    { name: "Matthew", slug: "matthew" },
    { name: "Mark", slug: "mark" },
    { name: "Luke", slug: "luke" },
    { name: "John", slug: "john" },
    { name: "Acts", slug: "acts" },
    { name: "Romans", slug: "romans" },
    { name: "1 Corinthians", slug: "1-corinthians" },
    { name: "2 Corinthians", slug: "2-corinthians" },
    { name: "Galatians", slug: "galatians" },
    { name: "Ephesians", slug: "ephesians" },
    { name: "Philippians", slug: "philippians" },
    { name: "Colossians", slug: "colossians" },
    { name: "1 Thessalonians", slug: "1-thessalonians" },
    { name: "2 Thessalonians", slug: "2-thessalonians" },
    { name: "1 Timothy", slug: "1-timothy" },
    { name: "2 Timothy", slug: "2-timothy" },
    { name: "Titus", slug: "titus" },
    { name: "Philemon", slug: "philemon" },
    { name: "Hebrews", slug: "hebrews" },
    { name: "James", slug: "james" },
    { name: "1 Peter", slug: "1-peter" },
    { name: "2 Peter", slug: "2-peter" },
    { name: "1 John", slug: "1-john" },
    { name: "2 John", slug: "2-john" },
    { name: "3 John", slug: "3-john" },
    { name: "Jude", slug: "jude" },
    { name: "Revelation", slug: "revelation" },
  ],
}

export const bibleBookAbbrevBySlug = {
  genesis: "gn",
  exodus: "ex",
  leviticus: "lv",
  numbers: "nm",
  deuteronomy: "dt",
  joshua: "js",
  judges: "jud",
  ruth: "rt",
  "1-samuel": "1sm",
  "2-samuel": "2sm",
  "1-kings": "1kgs",
  "2-kings": "2kgs",
  "1-chronicles": "1ch",
  "2-chronicles": "2ch",
  ezra: "ezr",
  nehemiah: "ne",
  esther: "et",
  job: "job",
  psalms: "ps",
  proverbs: "prv",
  ecclesiastes: "ec",
  "song-of-solomon": "so",
  isaiah: "is",
  jeremiah: "jr",
  lamentations: "lm",
  ezekiel: "ez",
  daniel: "dn",
  hosea: "ho",
  joel: "jl",
  amos: "am",
  obadiah: "ob",
  jonah: "jn",
  micah: "mi",
  nahum: "na",
  habakkuk: "hk",
  zephaniah: "zp",
  haggai: "hg",
  zechariah: "zc",
  malachi: "ml",
  matthew: "mt",
  mark: "mk",
  luke: "lk",
  john: "jo",
  acts: "act",
  romans: "rm",
  "1-corinthians": "1co",
  "2-corinthians": "2co",
  galatians: "gl",
  ephesians: "eph",
  philippians: "ph",
  colossians: "cl",
  "1-thessalonians": "1ts",
  "2-thessalonians": "2ts",
  "1-timothy": "1tm",
  "2-timothy": "2tm",
  titus: "tt",
  philemon: "phm",
  hebrews: "hb",
  james: "jm",
  "1-peter": "1pe",
  "2-peter": "2pe",
  "1-john": "1jo",
  "2-john": "2jo",
  "3-john": "3jo",
  jude: "jd",
  revelation: "re",
}

export const bibleBookNameBySlug = {
  genesis: "Genesis",
  exodus: "Exodus",
  leviticus: "Leviticus",
  numbers: "Numbers",
  deuteronomy: "Deuteronomy",
  joshua: "Joshua",
  judges: "Judges",
  ruth: "Ruth",
  "1-samuel": "1 Samuel",
  "2-samuel": "2 Samuel",
  "1-kings": "1 Kings",
  "2-kings": "2 Kings",
  "1-chronicles": "1 Chronicles",
  "2-chronicles": "2 Chronicles",
  ezra: "Ezra",
  nehemiah: "Nehemiah",
  esther: "Esther",
  job: "Job",
  psalms: "Psalms",
  proverbs: "Proverbs",
  ecclesiastes: "Ecclesiastes",
  "song-of-solomon": "Song of Solomon",
  isaiah: "Isaiah",
  jeremiah: "Jeremiah",
  lamentations: "Lamentations",
  ezekiel: "Ezekiel",
  daniel: "Daniel",
  hosea: "Hosea",
  joel: "Joel",
  amos: "Amos",
  obadiah: "Obadiah",
  jonah: "Jonah",
  micah: "Micah",
  nahum: "Nahum",
  habakkuk: "Habakkuk",
  zephaniah: "Zephaniah",
  haggai: "Haggai",
  zechariah: "Zechariah",
  malachi: "Malachi",
  matthew: "Matthew",
  mark: "Mark",
  luke: "Luke",
  john: "John",
  acts: "Acts",
  romans: "Romans",
  "1-corinthians": "1 Corinthians",
  "2-corinthians": "2 Corinthians",
  galatians: "Galatians",
  ephesians: "Ephesians",
  philippians: "Philippians",
  colossians: "Colossians",
  "1-thessalonians": "1 Thessalonians",
  "2-thessalonians": "2 Thessalonians",
  "1-timothy": "1 Timothy",
  "2-timothy": "2 Timothy",
  titus: "Titus",
  philemon: "Philemon",
  hebrews: "Hebrews",
  james: "James",
  "1-peter": "1 Peter",
  "2-peter": "2 Peter",
  "1-john": "1 John",
  "2-john": "2 John",
  "3-john": "3 John",
  jude: "Jude",
  revelation: "Revelation",
}
